config/routes.rb
Rails.application.routes.draw do
  root 'grids#index'
  resources :grids
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/grid.rb
class Grid < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/grids_controller.rb
class GridsController < ApplicationController
  before_action :set_grid, only: %i[show edit update destroy]

  # GET /grids or /grids.json
  def index
    @grids = Grid.all
    @start_nodes = Grid.where("payload->>'start_node' = '[0, 0]'")
  end

  # GET /grids/1 or /grids/1.json
  def show; end

  # GET /grids/new
  def new
    @grid = Grid.new
  end

  # GET /grids/1/edit
  def edit; end

  # POST /grids or /grids.json
  def create
    @grid = Grid.new(grid_params)

    respond_to do |format|
      if @grid.save
        format.html { redirect_to grid_url(@grid), notice: 'Grid was successfully created.' }
        format.json { render :show, status: :created, location: @grid }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @grid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grids/1 or /grids/1.json
  def update
    payload = JSON.parse(params[:grid][:payload])
    @grid.payload = payload

    respond_to do |format|
      if @grid.save
        format.html { redirect_to grid_url(@grid), notice: 'Grid was successfully updated.' }
        format.json { render :show, status: :ok, location: @grid }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @grid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grids/1 or /grids/1.json
  def destroy
    @grid.destroy

    respond_to do |format|
      format.html { redirect_to grids_url, notice: 'Grid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_grid
    @grid = Grid.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def grid_params
    params.require(:grid).permit(:payload)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grids_helper.rb
module GridsHelper
end

app/views/grids/_form.html.erb
<%= form_with(model: grid) do |form| %>
  <% if grid.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(grid.errors.count, "error") %> prohibited this grid from being saved:</h2>
      <ul>
        <% grid.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :payload, style: "display: block" %>
    <%= form.text_area :payload, value: grid.payload.to_json %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/grids/_grid.html.erb
<div id="<%= dom_id grid %>">
  <p>
    <strong>Payload:</strong>
    <%= grid.payload %>
  </p>
  <%= content_tag(:canvas, "", data: {
    controller: "grid",
    grid_payload: grid.payload,
  }) %>
</div>

app/views/grids/edit.html.erb
<h1>Editing grid</h1>

<%= render "form", grid: @grid %>

<br>

<div>
  <%= link_to "Show this grid", @grid %> |
  <%= link_to "Back to grids", grids_path %>
</div>

app/views/grids/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Grids</h1>
<div class="jsonb-nodes">
  <h3>Grids with [2, 2] start nodes</h3>
  <% @start_nodes.each do |grid| %>
    <p><%= link_to "Show grid", grid %></p>
  <% end %>
</div>
<div id="grids">
  <% @grids.each do |grid| %>
    <%= render grid %>
    <p>
      <%= link_to "Show this grid", grid %>
    </p>
  <% end %>
</div>
<%= link_to "New grid", new_grid_path %>

app/views/grids/new.html.erb
<h1>New grid</h1>

<%= render "form", grid: @grid %>

<br>

<div>
  <%= link_to "Back to grids", grids_path %>
</div>

app/views/grids/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @grid %>

<div>
  <%= link_to "Edit this grid", edit_grid_path(@grid) %> |
  <%= link_to "Back to grids", grids_path %>

  <%= button_to "Destroy this grid", @grid, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Video</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>